import type { DeviceCategory, DeviceItem } from './types';

export const DEVICE_CATEGORY_LABELS: Record<DeviceCategory, string> = {
  universal: 'Готовые',
  solar: 'Солнечные',
  boards: 'Платы',
};

export const DEVICE_DATA: Record<DeviceCategory, DeviceItem[]> = {
  universal: [
    {
      title: 'ThinkNode M1',
      image: '/img/wiki/thinknode-m1.webp',
      alt: 'ThinkNode M1',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Низкое энергопотребление и дисплей E-Ink, который отлично читается на солнце и экономит батарею.',
        'Подходит для портативных узлов, выездных ретрансляторов и походной навигации.',
      ],
      price: '≈ 5 800 ₽',
      href: 'https://ali.click/iqp631v?erid=2SDnjdGLkt9',
      tech: 'NRF',
    },
    {
      title: 'SenseCAP T1000-E',
      image: '/img/wiki/sensecap-t1000e.webp',
      alt: 'SenseCAP T1000-E',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Компактное устройство на nRF52840 с интегрированным GPS и высокой автономностью.',
        'Хороший вариант для мобильных ретрансляторов, трекинга и длительного полевого использования.',
      ],
      price: '≈ 4 500 ₽',
      href: 'https://ali.click/gop6314?erid=2SDnjbqKT6q',
      tech: 'NRF',
    },
    {
      title: 'Heltec MeshPocket',
      image: '/img/wiki/heltec-meshpocket.webp',
      alt: 'Heltec MeshPocket',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Готовое решение с E-Ink дисплеем, магнитной зарядкой и встроенным павербанком (в зависимости от комплектации).',
        'Удобно как повседневная портативная нода «из коробки».',
      ],
      price: '≈ 7 000 ₽',
      href: 'https://ali.click/orp631d?erid=2SDnjdyrQmo',
      tech: 'NRF',
    },
    {
      title: 'LILYGO TTGO T-Echo',
      image: '/img/wiki/lilygo-ttgo-t-echo.webp',
      alt: 'LILYGO TTGO T-Echo',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Портативное устройство на nRF52840 с E-Ink и GPS для автономной работы.',
        'Часто выбирают для походов, трекинга и длительных выездов без частой подзарядки.',
      ],
      price: '≈ 5 000 ₽',
      href: 'https://ali.click/btp631w?erid=2SDnjexBwUu',
      tech: 'NRF',
    },
    {
      title: 'Wio Tracker L1 Pro',
      image: '/img/wiki/wio-tracker-l1-pro.webp',
      alt: 'Wio Tracker L1 Pro',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Готовая нода с GPS в компактном корпусе, ориентированная на мобильные и автономные сценарии.',
        'Подходит для выездных станций, навигации и трекинга.',
      ],
      price: '≈ 6 000 ₽',
      href: 'https://ali.click/cup631b?erid=2SDnjcLyYDf',
      tech: 'NRF',
    },
    {
      title: 'LILYGO T-Deck Plus',
      image: '/img/wiki/lilygo-t-deck-plus.webp',
      alt: 'LILYGO T-Deck Plus',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Мощное устройство на ESP32-S3 с цветным экраном и клавиатурой для локального управления.',
        'Функционально и удобно в поле, но потребляет больше энергии, чем nRF-решения.',
      ],
      price: '≈ 8 000 ₽',
      href: 'https://ali.click/dvp631v?erid=2SDnjcubGRF',
      tech: 'ESP',
    },
    {
      title: 'T-LoRa Pager',
      image: '/img/wiki/t-lora-pager.webp',
      alt: 'T-LoRa Pager',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Компактный пейджер-формат для обмена сообщениями в Meshtastic.',
        'Удобен для повседневного ношения, локальных тестов и личной связи.',
      ],
      price: '≈ 8 000 ₽',
      href: 'https://ali.click/2wp631a?erid=2SDnjdGM6N5',
      tech: 'ESP',
    },
    {
      title: 'Meshtiny Mini Pocket',
      image: '/img/wiki/meshtiny-mini-pocket.webp',
      alt: 'Meshtiny Meshtastic Mini Pocket',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Ультракомпактная карманная нода на nRF52 + SX1262 для повседневного использования.',
        'Небольшой размер и хорошая автономность делают её удобной как «личный клиент» Meshtastic.',
      ],
      price: '≈ 5 500 ₽',
      href: 'https://ali.click/typ631s?erid=2SDnjeftQs3',
      tech: 'NRF',
    },
    {
      title: 'Heltec V4 18650 Touchscreen',
      image: '/img/wiki/heltecv4-touchscreen.webp',
      alt: 'Heltec V4 18650 Touchscreen',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Функциональное устройство на базе ESP32-S3 с увеличенным экраном и версией с тачскрином.',
        'Батарея покупается отдельно, хорошо подходит для сценариев, где нужен дисплей и расширенное управление.',
      ],
      price: '≈ 7 000 ₽',
      href: 'https://ali.click/yzp6315?erid=2SDnjbqL84h',
      tech: 'ESP',
    },
    {
      title: 'Heltec V4 Case Ready',
      image: '/img/wiki/v4-case-ready.webp',
      alt: 'Heltec V4 Case Ready',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Нода на Heltec V4 в комплекте с корпусом, GPS и антенной.',
        'Требует самостоятельной сборки, батарея покупается отдельно.',
      ],
      price: '≈ 3 200 ₽',
      href: 'https://ali.click/82q631h?erid=2SDnjcubbuB',
      tech: 'ESP',
    },
    {
      title: 'T-Beam 1W',
      image: '/img/wiki/1w-node.webp',
      alt: 'T-Beam 1W',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Сверхмощное устройство на базе ESP32 с GPS.',
        'Рекомендуется для специальных сценариев вне плотной городской сети, где действительно нужна повышенная мощность.',
      ],
      price: '≈ 5 000 ₽',
      href: 'https://ali.click/83q631v?erid=2SDnjdLoPh3',
      purchaseConfirm: {
        title: 'Внимание: повышенная мощность',
        description:
          'Эта нода рассчитана на высокий уровень мощности. В плотной сети она может создавать лишние помехи и ухудшать работу меш-сети вокруг вас. Используйте её только если понимаете последствия и действительно нуждаетесь в такой мощности.',
        confirmLabel: 'Подтверждаю и перейти',
        cancelLabel: 'Отмена',
      },
      tech: 'ESP',
    },
    {
      title: 'T-Echo Plus',
      image: '/img/wiki/techoplus.webp',
      alt: 'T-Echo Plus',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Экономичная nRF52840-нода с BME280 и GPS, рассчитанная на длительную автономную работу.',
        'Оснащается увеличенной батареей и подходит для портативных сценариев.',
      ],
      price: '≈ 6 000 ₽',
      href: 'https://ali.click/4vq631l?erid=2SDnjbosUi5',
      tech: 'NRF',
    },
  ],
  solar: [
    {
      title: 'D5 Mini Solar Kit (Heltec V3)',
      image: '/img/wiki/d5-mini-solar-kit.webp',
      alt: 'D5 Mini Solar Kit',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Автономный солнечный комплект на базе Heltec V3 для стационарных и удалённых точек сети.',
        'Хорошо подходит для ретрансляторов, сенсорных узлов и длительной уличной установки.',
      ],
      price: '≈ 6 000 ₽',
      href: 'https://ali.click/9cq631m?erid=2SDnjdswU6D',
      tech: 'ESP',
    },
    {
      title: 'Gitfus Solar Node',
      image: '/img/wiki/gitfus-solar-node.webp',
      alt: 'Gitfus Solar Node',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Экономичная солнечная нода на NRF для автономных установок.',
        'В зимних условиях штатной панели может быть недостаточно, лучше ориентироваться на сезонные сценарии.',
      ],
      price: '≈ 2 000 ₽',
      href: 'https://ali.click/ugq631l?erid=2SDnjcnCLTK',
      tech: 'NRF',
    },
    {
      title: 'SenseCAP Solar Node',
      image: '/img/wiki/sensecap-solar-node.webp',
      alt: 'SenseCAP Solar Node',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Готовая солнечная нода от Seeed Studio для длительной автономной работы на улице.',
        'Прочный форм-фактор и низкое энергопотребление подходят для удалённых стационарных узлов.',
      ],
      price: '≈ 7 000 ₽',
      href: 'https://ali.click/qhq631e?erid=2SDnjd8xAQ9',
      tech: 'NRF',
    },
  ],
  boards: [
    {
      title: 'Heltec WiFi LoRa 32 (V3)',
      image: '/img/wiki/heltec-wifi-lora32-v3.webp',
      alt: 'Heltec WiFi LoRa 32 V3',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Популярная ESP-плата на ESP32-S3 с OLED и SX1262, компактная и стабильная.',
        'Часто используется в сенсорных, экспериментальных и стационарных DIY-нодах.',
      ],
      price: '≈ 1 500 ₽',
      href: 'https://ali.click/ziq631d?erid=2SDnjdd7vkh',
      tech: 'ESP',
      popular: true,
      videoHref: 'https://www.youtube.com/watch?v=puI6pSaGfsc',
      videoLabel: 'Видео сборки',
    },
    {
      title: 'Heltec V4 / Heltec Wireless Stick Lite V4',
      image: '/img/wiki/heltec-wireless-stick-lite-v4.webp',
      alt: 'Heltec Wireless Stick Lite V4',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Новое поколение Heltec на ESP32-S3 с SX1262 и улучшенной схемотехникой.',
        'Подходит для автономных узлов, ретрансляторов и компактных DIY-сборок.',
      ],
      price: '≈ 2 000 ₽',
      href: 'https://ali.click/1kq631v?erid=2SDnje2qjGD',
      tech: 'ESP',
      popular: true,
    },
    {
      title: 'FakeTec V5.5',
      image: '/img/wiki/faketec.webp',
      alt: 'FakeTec V5.5',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ❌', off: true }],
      shippingLabel: 'БЫСТРАЯ ДОСТАВКА',
      descriptionLines: [
        'Компактная плата на NRF (FakeTec v5.5) с возможностью подключения GPS и датчиков.',
        'Подходит для бюджетных и компактных DIY-сборок.',
      ],
      price: '≈ 2 000 ₽',
      href: 'https://www.avito.ru/domodedovo/telefony/faketec_v5_rev_b_meshtasticmeshcore_7914693905',
      ctaLabel: 'Avito',
      tech: 'NRF',
    },
    {
      title: 'Heltec V4 + Case',
      image: '/img/wiki/heltec-v4-case.webp',
      alt: 'Heltec V4 with Case',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Комплект Heltec V4 с корпусом для быстрой сборки компактной ESP-ноды.',
        'Удобный вариант, если нужна готовая «коробка» с минимальной доработкой.',
      ],
      price: '≈ 3 000 ₽',
      href: 'https://ali.click/3lq631s?erid=2SDnjeU3X45',
      tech: 'ESP',
    },
    {
      title: 'Heltec T114',
      image: '/img/wiki/heltec-t114.webp',
      alt: 'Heltec T114',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'nRF-плата с TFT 1.14″ и GPS (в версиях с GPS) для портативных автономных сборок.',
        'Часто выбирают как энергоэффективную основу для походных устройств.',
      ],
      price: '≈ 3 300 ₽',
      href: 'https://ali.click/rnq631y?erid=2SDnjc7ezcH',
      tech: 'NRF',
    },
    {
      title: 'Heltec T114 Naked',
      image: '/img/wiki/heltec-t114-naked.webp',
      alt: 'Heltec T114 Naked',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Упрощенная версия T114 без корпуса и GPS для более бюджетной сборки.',
        'Подходит для проектов, где важны цена и автономность nRF-платформы.',
      ],
      price: '≈ 2 200 ₽',
      href: 'https://ali.click/9mq6316?erid=2SDnjerHLHF',
      tech: 'NRF',
    },
    {
      title: 'Wio Tracker L1 E-ink',
      image: '/img/wiki/wio-tracker-l1-eink.webp',
      alt: 'Wio Tracker L1 E-ink',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ❌', off: true }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Плата на nRF с E-Ink и GPS для мобильных и походных сценариев.',
        'Сочетает хорошую автономность, компактность и удобство чтения на солнце.',
      ],
      price: '≈ 3 900 ₽',
      href: 'https://ali.click/kpq631h?erid=2SDnjckigeu',
      tech: 'NRF',
    },
    {
      title: 'LILYGO TTGO T-Beam',
      image: '/img/wiki/lilygo-ttgo-t-beam.webp',
      alt: 'LILYGO TTGO T-Beam',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'Классическая ESP-плата со встроенным GPS и питанием от 18650.',
        'Удобна для полевых узлов, автомобильных станций и тестов с полной автономностью.',
      ],
      price: '≈ 3 500 ₽',
      href: 'https://ali.click/kqq631j?erid=2SDnjd8xVt5',
      tech: 'ESP',
    },
    {
      title: 'Heltec Wireless Stick Lite / Mesh Nod',
      image: '/img/wiki/heltec-wireless-stick-lite.webp',
      alt: 'Heltec Wireless Stick Lite',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Упрощенная ESP-плата без GPS/дисплея для сенсорных станций и ретрансляторов.',
        'Простая интеграция и компактный размер делают её удобной для стационарных сборок.',
      ],
      price: '≈ 1 300 ₽',
      href: 'https://ali.click/trq6312?erid=2SDnjdbeGxH',
      tech: 'ESP',
    },
    {
      title: 'Heltec LoRa Wireless Paper',
      image: '/img/wiki/heltec-wireless-paper.webp',
      alt: 'Heltec LoRa Wireless Paper',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'ESP-плата с E-Ink 2.9″ и SX1262 для автономных компактных нод.',
        'Подходит, когда нужен дисплей с отличной читаемостью и умеренным энергопотреблением.',
      ],
      price: '≈ 1 500 ₽',
      href: 'https://ali.click/5sq631u?erid=2SDnjdoWBD3',
      tech: 'ESP',
    },
    {
      title: 'Heltec Stick /GPS',
      image: '/img/wiki/heltec-stick-gps.webp',
      alt: 'Heltec Stick GPS',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ✅' }],
      descriptionLines: [
        'ESP-версия Heltec Stick со встроенным GPS для мобильных и тестовых сценариев.',
        'Хороший компромисс между компактностью, функциональностью и стоимостью.',
      ],
      price: '≈ 1 800 ₽',
      href: 'https://ali.click/3tq631w?erid=2SDnjeDDyiZ',
      tech: 'ESP',
    },
    {
      title: 'LoRa 32 LILYGO / LILYGO T3 S3',
      image: '/img/wiki/lilygo-lora32-t3.webp',
      alt: 'LoRa 32 LILYGO T3 S3',
      badges: [{ label: 'Bluetooth ✅' }, { label: 'Wi-Fi ✅' }, { label: 'GPS ❌', off: true }],
      descriptionLines: [
        'Компактная ESP-плата с OLED и LoRa, проверенная в DIY-проектах.',
        'Подходит для переносных и стационарных узлов, сенсорных станций и выездных стендов.',
      ],
      price: '≈ 2 000 ₽',
      href: 'https://ali.click/xvq631g?erid=2SDnjc99KNZ',
      tech: 'ESP',
    },
  ],
};
